### ISSUE TITLE
MangaEden directory url changed

### ISSUE THREAD

**Issue by Curlybear** [bendem/MangaScraper#2]
https://github.com/bendem/MangaScraper/blob/master/src/main/java/be/bendem/manga/scraper/implementations/MangaEdenScraper.java#L24

http://www.mangaeden.com/en-directory/ -> http://www.mangaeden.com/en/en-directory/

**Comment by bendem** [comment]
Waiting implementation of http://www.mangaeden.com/api/

**Comment by bendem** [comment]
https://github.com/bendem/MangaScraper/commit/431f1d8700de650b6d1bb6184fde1f743b6a9b73
